volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env

    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static:/app/collected_static
      - media:/app/media
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn kittygram_backend.wsgi:application --bind 0.0.0.0:8000"
  frontend:
    env_file: .env
    build: ./frontend/
    depends_on:
      - backend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/app/frontend_build
  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/app/static
      - media:/app/media
